[theme]
primaryColor = "#00ac69"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#1a0a38"
textColor = "#2c3e50"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
# Lista di domini consentiti per CORS
allowedOrigins = ["https://artificialitalian.it"]
maxUploadSize = 200
maxMessageSize = 200
port = 8501

[browser]
serverAddress = "artificialitalian.it"
gatherUsageStats = false

[global]
showWarningOnDirectExecution = true
